/*
  Zentrale Produktdaten fuer WESTBERG.
  Neue Produkte koennen hier ergaenzt werden, ohne HTML-Markup anzufassen.
*/
const WESTBERG_PRODUCTS = [
  {
    id: "jeanshose-lang",
    name: "WESTBERG Jeanshose lang",
    price: 79.99,
    description: "Weit geschnittene Denim-Hose in hellem Blue-Wash fuer entspannte City-Looks.",
    category: "herren",
    image: "assets/jeans-long-model.png",
    images: ["assets/jeans-long-model.png", "assets/jeans-long-product.png"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Light Denim", value: "#9fbfe0" }],
    material: "60% recyceltes Plastik, 40% recycelte Kleidung",
    stock: 18,
  },
  {
    id: "jeanshose-kurz",
    name: "WESTBERG Jeanshose kurz",
    price: 49.99,
    description: "Bermuda-Shorts mit geradem Bein, cleanem Finish und sommerlichem Denim-Gefuehl.",
    category: "herren",
    image: "assets/jeans-short-model.png",
    images: ["assets/jeans-short-model.png", "assets/jeans-short-product.png"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Light Denim", value: "#a6c6e5" }],
    material: "60% recyceltes Plastik, 40% recycelte Kleidung",
    stock: 22,
  },
  {
    id: "tshirt",
    name: "WESTBERG T-Shirt",
    price: 29.99,
    description: "Cleanes White Tee mit kleinem WESTBERG Brustlogo und weicher Premium-Haptik.",
    category: "unisex",
    image: "assets/tshirt-model.jpeg",
    images: ["assets/tshirt-model.jpeg", "assets/tshirt-front.jpeg", "assets/tshirt-back.jpeg"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [{ name: "White", value: "#f7f7f3" }],
    material: "60% recyceltes Plastik, 40% recycelte Kleidung",
    stock: 35,
  },
  {
    id: "jogginghose",
    name: "WESTBERG Jogginghose",
    price: 59.99,
    description: "Soft-Touch Jogger mit elastischem Bund, Tunnelzug und klarer Silhouette.",
    category: "unisex",
    image: "assets/joggers.png",
    images: ["assets/joggers.png"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Sky Blue", value: "#9fd0ff" }],
    material: "60% recyceltes Plastik, 40% recycelte Kleidung",
    stock: 24,
  },
  {
    id: "hoodie",
    name: "WESTBERG Hoodie",
    price: 69.99,
    description: "Minimalistischer Hoodie in Sky Blue mit Kanga-Tasche und weichem Fleece-Inside.",
    category: "unisex",
    image: "assets/hoodie.png",
    images: ["assets/hoodie.png"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Sky Blue", value: "#9fd0ff" }],
    material: "60% recyceltes Plastik, 40% recycelte Kleidung",
    stock: 17,
  },
  {
    id: "jogginganzug",
    name: "WESTBERG Jogginganzug",
    price: 119.99,
    description: "Matching Set aus Hoodie und Jogginghose fuer einen abgestimmten Everyday-Look.",
    category: "unisex",
    image: "assets/tracksuit-model.png",
    images: ["assets/tracksuit-model.png", "assets/hoodie.png", "assets/joggers.png"],
    sizes: ["XS", "S", "M", "L", "XL", "XXL"],
    colors: [{ name: "Sky Blue", value: "#9fd0ff" }],
    material: "60% recyceltes Plastik, 40% recycelte Kleidung",
    stock: 12,
  },
  {
    id: "cap",
    name: "WESTBERG Cap",
    price: 24.99,
    description: "Klassische Dad Cap mit hochwertiger Stickerei, verfuegbar in vier Farbvarianten.",
    category: "accessoires",
    image: "assets/cap-beige.png",
    images: ["assets/cap-beige.png", "assets/cap-blue.png", "assets/cap-white.png", "assets/cap-black.png"],
    sizes: ["One Size"],
    colors: [
      { name: "Beige", value: "#d4b98c", image: "assets/cap-beige.png" },
      { name: "Blue", value: "#9fc7fb", image: "assets/cap-blue.png" },
      { name: "White", value: "#f6f6f1", image: "assets/cap-white.png" },
      { name: "Black", value: "#111111", image: "assets/cap-black.png" },
    ],
    material: "60% recyceltes Plastik, 40% recycelte Kleidung",
    stock: 40,
  },
];
